# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rovers.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crovers.proto\"\x18\n\nmapRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x08mapReply\x12\x0b\n\x03map\x18\x01 \x03(\t\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x03 \x01(\x05\"\"\n\x14\x63ommandStreamRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x12\x63ommandStreamReply\x12\x0c\n\x04\x63mds\x18\x01 \x01(\t\"4\n\x10serialNumRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01i\x18\x02 \x01(\x05\x12\t\n\x01j\x18\x03 \x01(\x05\"#\n\x0eserialNumReply\x12\x11\n\tserialNum\x18\x01 \x01(\t\",\n\x10\x63ompletedRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"\x1d\n\x0e\x63ompletedReply\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\"8\n\npinRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tserialNum\x18\x02 \x01(\t\x12\x0b\n\x03pin\x18\x03 \x01(\t\"\x17\n\x08pinReply\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2\x85\x02\n\x06rovers\x12\"\n\x06getMap\x12\x0b.mapRequest\x1a\t.mapReply\"\x00\x12@\n\x10getCommandStream\x12\x15.commandStreamRequest\x1a\x13.commandStreamReply\"\x00\x12\x35\n\rgetMineSerial\x12\x11.serialNumRequest\x1a\x0f.serialNumReply\"\x00\x12\x39\n\x11\x63ompletedCommands\x12\x11.completedRequest\x1a\x0f.completedReply\"\x00\x12#\n\x07sendPin\x12\x0b.pinRequest\x1a\t.pinReply\"\x00\x42/\n\x17io.grpc.examples.roversB\x0bRoversProtoP\x01\xa2\x02\x04RVRPb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rovers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027io.grpc.examples.roversB\013RoversProtoP\001\242\002\004RVRP'
  _globals['_MAPREQUEST']._serialized_start=16
  _globals['_MAPREQUEST']._serialized_end=40
  _globals['_MAPREPLY']._serialized_start=42
  _globals['_MAPREPLY']._serialized_end=93
  _globals['_COMMANDSTREAMREQUEST']._serialized_start=95
  _globals['_COMMANDSTREAMREQUEST']._serialized_end=129
  _globals['_COMMANDSTREAMREPLY']._serialized_start=131
  _globals['_COMMANDSTREAMREPLY']._serialized_end=165
  _globals['_SERIALNUMREQUEST']._serialized_start=167
  _globals['_SERIALNUMREQUEST']._serialized_end=219
  _globals['_SERIALNUMREPLY']._serialized_start=221
  _globals['_SERIALNUMREPLY']._serialized_end=256
  _globals['_COMPLETEDREQUEST']._serialized_start=258
  _globals['_COMPLETEDREQUEST']._serialized_end=302
  _globals['_COMPLETEDREPLY']._serialized_start=304
  _globals['_COMPLETEDREPLY']._serialized_end=333
  _globals['_PINREQUEST']._serialized_start=335
  _globals['_PINREQUEST']._serialized_end=391
  _globals['_PINREPLY']._serialized_start=393
  _globals['_PINREPLY']._serialized_end=416
  _globals['_ROVERS']._serialized_start=419
  _globals['_ROVERS']._serialized_end=680
# @@protoc_insertion_point(module_scope)
